version: 0.2

phases:
  install:
    commands:
      - echo "Installing Maven"
      - mvn --version
  build:
    commands:
      - echo "Building WAR file"
      - mvn clean package
artifacts:
  files:
    - appspec.yml
    - target/webapp.war
    - scripts/restart_tomcat.sh
  discard-paths: yes
